import os
import pandas as pd
import numpy as np
from datetime import datetime
from typing import Dict, Any, Optional
from backend.app.core.logging import logger
from backend.app.core.config import settings
from backend.app.geospatial.distance import (
    find_nearest_point,
    compute_fire_proximity_kernels,
)


class GeospatialFusionEngine:
    """
    Spatiotemporal fusion engine combining multi-source satellite, meteorology,
    fire proximity, and in-situ ground truth into an ML-ready feature dataset.
    """

    def __init__(
        self,
        cpcb_df: Optional[pd.DataFrame] = None,
        insat_df: Optional[pd.DataFrame] = None,
        tropomi_df: Optional[pd.DataFrame] = None,
        firms_df: Optional[pd.DataFrame] = None,
        era5_df: Optional[pd.DataFrame] = None,
    ):
        self.cpcb_df = cpcb_df
        self.insat_df = insat_df
        self.tropomi_df = tropomi_df
        self.firms_df = firms_df
        self.era5_df = era5_df

    def load_latest_processed_data(self):
        """
        Loads the latest processed Parquet datasets generated by Phase 2 ingestion.
        """
        cpcb_path = os.path.join(settings.PROCESSED_DATA_DIR, "cpcb", "cpcb_latest.parquet")
        insat_path = os.path.join(settings.PROCESSED_DATA_DIR, "insat_aod", "insat_aod_latest.parquet")
        tropomi_path = os.path.join(settings.PROCESSED_DATA_DIR, "tropomi", "tropomi_latest.parquet")
        firms_path = os.path.join(settings.PROCESSED_DATA_DIR, "firms", "firms_latest.parquet")
        era5_path = os.path.join(settings.PROCESSED_DATA_DIR, "era5", "era5_latest.parquet")

        if os.path.exists(cpcb_path):
            self.cpcb_df = pd.read_parquet(cpcb_path)
        if os.path.exists(insat_path):
            self.insat_df = pd.read_parquet(insat_path)
        if os.path.exists(tropomi_path):
            self.tropomi_df = pd.read_parquet(tropomi_path)
        if os.path.exists(firms_path):
            self.firms_df = pd.read_parquet(firms_path)
        if os.path.exists(era5_path):
            self.era5_df = pd.read_parquet(era5_path)

        logger.info("Loaded all processed datasets into GeospatialFusionEngine")

    def fuse_single_point(
        self,
        lat: float,
        lon: float,
        timestamp: Optional[datetime] = None,
        elevation_m: float = 150.0,
    ) -> Dict[str, Any]:
        """
        Fuses all satellite, meteorological, fire, and temporal features for a single location.
        """
        dt = timestamp or datetime.utcnow()
        features: Dict[str, Any] = {
            "latitude": lat,
            "longitude": lon,
            "elevation_m": elevation_m,
            # Temporal features
            "hour": dt.hour,
            "day_of_year": dt.timetuple().tm_yday,
            "month": dt.month,
            "day_of_week": dt.weekday(),
            "is_weekend": 1 if dt.weekday() >= 5 else 0,
        }

        # 1. Satellite AOD (INSAT-3D)
        if self.insat_df is not None and not self.insat_df.empty:
            nearest_insat, dist = find_nearest_point(lat, lon, self.insat_df)
            features["aod_insat"] = nearest_insat.get("aod_550nm", 0.45)
            features["dist_to_aod_km"] = round(dist, 1)
        else:
            features["aod_insat"] = 0.45
            features["dist_to_aod_km"] = 0.0

        # 2. Satellite Trace Gases (TROPOMI)
        if self.tropomi_df is not None and not self.tropomi_df.empty:
            nearest_tropomi, dist = find_nearest_point(lat, lon, self.tropomi_df)
            features["hcho_column"] = nearest_tropomi.get("hcho_column", 8.0)
            features["no2_column"] = nearest_tropomi.get("no2_column", 15.0)
            features["so2_column"] = nearest_tropomi.get("so2_column", 2.0)
            features["co_column"] = nearest_tropomi.get("co_column", 180.0)
            features["dist_to_tropomi_km"] = round(dist, 1)
        else:
            features["hcho_column"] = 8.0
            features["no2_column"] = 15.0
            features["so2_column"] = 2.0
            features["co_column"] = 180.0
            features["dist_to_tropomi_km"] = 0.0

        # 3. Meteorology & Boundary Layer (ERA5)
        if self.era5_df is not None and not self.era5_df.empty:
            nearest_era5, dist = find_nearest_point(lat, lon, self.era5_df)
            features["temperature_2m"] = nearest_era5.get("temp_c", 28.0)
            features["dewpoint_2m"] = nearest_era5.get("dewpoint_c", 18.0)
            features["relative_humidity"] = nearest_era5.get("relative_humidity", 55.0)
            features["wind_u"] = nearest_era5.get("u10", 2.0)
            features["wind_v"] = nearest_era5.get("v10", -1.5)
            features["wind_speed"] = nearest_era5.get("wind_speed", 2.5)
            features["wind_direction"] = nearest_era5.get("wind_direction_deg", 310.0)
            features["boundary_layer_height"] = nearest_era5.get("pblh_m", 550.0)
            features["surface_pressure"] = nearest_era5.get("sp_hpa", 995.0)
            features["total_precipitation"] = nearest_era5.get("tp_mm", 0.0)
        else:
            features["temperature_2m"] = 28.0
            features["dewpoint_2m"] = 18.0
            features["relative_humidity"] = 55.0
            features["wind_u"] = 2.0
            features["wind_v"] = -1.5
            features["wind_speed"] = 2.5
            features["wind_direction"] = 310.0
            features["boundary_layer_height"] = 550.0
            features["surface_pressure"] = 995.0
            features["total_precipitation"] = 0.0

        # 4. Fire Proximity Kernels (NASA FIRMS)
        if self.firms_df is not None and not self.firms_df.empty:
            fire_kernels = compute_fire_proximity_kernels(lat, lon, self.firms_df)
            features.update(fire_kernels)
        else:
            features.update({
                "fire_count_5km": 0,
                "fire_count_25km": 0,
                "fire_frp_5km": 0.0,
                "fire_frp_25km": 0.0,
                "dist_to_nearest_fire_km": 999.0,
            })

        return features

    def create_training_features(self) -> pd.DataFrame:
        """
        Builds the ground truth training dataset: joins CPCB target observations (PM2.5)
        with the multi-source fused feature set.
        """
        if self.cpcb_df is None or self.cpcb_df.empty:
            self.load_latest_processed_data()

        rows = []
        for _, station in self.cpcb_df.iterrows():
            lat = float(station["lat"])
            lon = float(station["lon"])
            dt = pd.to_datetime(station["timestamp"])

            # Extract fused features
            f = self.fuse_single_point(lat, lon, timestamp=dt)
            
            # Attach Ground Truth Target labels and Station info
            f["station_id"] = station["station_id"]
            f["station_name"] = station["name"]
            f["city"] = station["city"]
            f["state"] = station["state"]
            f["target_pm25"] = station.get("pm25", np.nan)
            f["target_pm10"] = station.get("pm10", np.nan)
            f["target_aqi"] = station.get("aqi", np.nan)
            f["target_aqi_category"] = station.get("aqi_category", "Moderate")
            f["target_dominant"] = station.get("dominant_pollutant", "PM2.5")

            rows.append(f)

        df = pd.DataFrame(rows)
        # Drop rows missing target PM2.5
        clean_train = df.dropna(subset=["target_pm25"]).copy()

        # Save to feature store
        os.makedirs(settings.FEATURE_STORE_DIR, exist_ok=True)
        out_path = os.path.join(settings.FEATURE_STORE_DIR, "training_features.parquet")
        clean_train.to_parquet(out_path, index=False, engine="pyarrow")
        clean_train.to_csv(os.path.join(settings.FEATURE_STORE_DIR, "training_features.csv"), index=False)
        logger.info(f"Saved {len(clean_train)} training records to {out_path}")

        return clean_train

    def create_national_grid_features(self, grid_df: pd.DataFrame) -> pd.DataFrame:
        """
        Generates fused features across the entire regularized spatial grid covering India.
        Used for continuous AI surface inference at unmonitored locations.
        """
        rows = []
        for _, cell in grid_df.iterrows():
            lat = float(cell["lat"])
            lon = float(cell["lon"])
            elev = float(cell.get("elevation_m", 150.0))

            f = self.fuse_single_point(lat, lon, elevation_m=elev)
            f["cell_id"] = cell["cell_id"]
            f["zone"] = cell.get("zone", "General")
            rows.append(f)

        df = pd.DataFrame(rows)
        os.makedirs(settings.FEATURE_STORE_DIR, exist_ok=True)
        out_path = os.path.join(settings.FEATURE_STORE_DIR, "national_grid_features.parquet")
        df.to_parquet(out_path, index=False, engine="pyarrow")
        logger.info(f"Saved {len(df)} nationwide grid feature cells to {out_path}")

        return df
